var annotated_dup =
[
    [ "AddressDTO", "class_address_d_t_o.html", null ],
    [ "AppComponent", "class_app_component.html", "class_app_component" ],
    [ "DatabaseClient", "class_database_client.html", "class_database_client" ],
    [ "DatabaseComponent", "class_database_component.html", "class_database_component" ],
    [ "DepartmentDTO", "class_department_d_t_o.html", null ],
    [ "DepartmentTrainingRelDTO", "class_department_training_rel_d_t_o.html", null ],
    [ "EmailDTO", "class_email_d_t_o.html", null ],
    [ "MemberAdressRelDTO", "class_member_adress_rel_d_t_o.html", null ],
    [ "MemberController", "class_member_controller.html", null ],
    [ "MemberDTO", "class_member_d_t_o.html", null ],
    [ "MemberEmailRelDTO", "class_member_email_rel_d_t_o.html", null ],
    [ "MemberMembershipRelDTO", "class_member_membership_rel_d_t_o.html", null ],
    [ "MemberPageDTO", "class_member_page_d_t_o.html", null ],
    [ "MemberPhonenumberRelDTO", "class_member_phonenumber_rel_d_t_o.html", null ],
    [ "MemberService", "class_member_service.html", "class_member_service" ],
    [ "MembershipDepartmentRelDTO", "class_membership_department_rel_d_t_o.html", null ],
    [ "MembershipDTO", "class_membership_d_t_o.html", null ],
    [ "MemberTrainingRelDTO", "class_member_training_rel_d_t_o.html", null ],
    [ "PageDTO", "class_page_d_t_o.html", null ],
    [ "PhoneNumberDTO", "class_phone_number_d_t_o.html", null ],
    [ "StaticController", "class_static_controller.html", null ],
    [ "StatusDTO", "class_status_d_t_o.html", null ],
    [ "SwaggerComponent", "class_swagger_component.html", "class_swagger_component" ],
    [ "TrainingDTO", "class_training_d_t_o.html", null ]
];